
INSTANCES = {
    "t2.nano":      {"vcpu":1,   "ram":0.5,   "storage":"EBS only",          "network":"Low to Moderate",   "family":"General Purpose"},
    "t2.micro":     {"vcpu":1,   "ram":1,     "storage":"EBS only",          "network":"Low to Moderate",   "family":"General Purpose"},
    "t2.small":     {"vcpu":1,   "ram":2,     "storage":"EBS only",          "network":"Low to Moderate",   "family":"General Purpose"},
    "t2.medium":    {"vcpu":2,   "ram":4,     "storage":"EBS only",          "network":"Low to Moderate",   "family":"General Purpose"},
    "t2.large":     {"vcpu":2,   "ram":8,     "storage":"EBS only",          "network":"Low to Moderate",   "family":"General Purpose"},
    "t2.xlarge":    {"vcpu":4,   "ram":16,    "storage":"EBS only",          "network":"Moderate",          "family":"General Purpose"},
    "t2.2xlarge":   {"vcpu":8,   "ram":32,    "storage":"EBS only",          "network":"Moderate",          "family":"General Purpose"},
    "t3.nano":      {"vcpu":2,   "ram":0.5,   "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.micro":     {"vcpu":2,   "ram":1,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.small":     {"vcpu":2,   "ram":2,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.medium":    {"vcpu":2,   "ram":4,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.large":     {"vcpu":2,   "ram":8,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.xlarge":    {"vcpu":4,   "ram":16,    "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3.2xlarge":   {"vcpu":8,   "ram":32,    "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.nano":     {"vcpu":2,   "ram":0.5,   "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.micro":    {"vcpu":2,   "ram":1,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.small":    {"vcpu":2,   "ram":2,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.medium":   {"vcpu":2,   "ram":4,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.large":    {"vcpu":2,   "ram":8,     "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.xlarge":   {"vcpu":4,   "ram":16,    "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "t3a.2xlarge":  {"vcpu":8,   "ram":32,    "storage":"EBS only",          "network":"Up to 5 Gigabit",   "family":"General Purpose"},
    "m5.large":     {"vcpu":2,   "ram":8,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5.xlarge":    {"vcpu":4,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5.2xlarge":   {"vcpu":8,   "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5.4xlarge":   {"vcpu":16,  "ram":64,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5.8xlarge":   {"vcpu":32,  "ram":128,   "storage":"EBS only",          "network":"10 Gigabit",        "family":"General Purpose"},
    "m5.12xlarge":  {"vcpu":48,  "ram":192,   "storage":"EBS only",          "network":"12 Gigabit",        "family":"General Purpose"},
    "m5.16xlarge":  {"vcpu":64,  "ram":256,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"General Purpose"},
    "m5.24xlarge":  {"vcpu":96,  "ram":384,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"General Purpose"},
    "m5a.large":    {"vcpu":2,   "ram":8,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5a.xlarge":   {"vcpu":4,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5a.2xlarge":  {"vcpu":8,   "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5a.4xlarge":  {"vcpu":16,  "ram":64,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5a.8xlarge":  {"vcpu":32,  "ram":128,   "storage":"EBS only",          "network":"10 Gigabit",        "family":"General Purpose"},
    "m5a.12xlarge": {"vcpu":48,  "ram":192,   "storage":"EBS only",          "network":"12 Gigabit",        "family":"General Purpose"},
    "m5a.16xlarge": {"vcpu":64,  "ram":256,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"General Purpose"},
    "m5a.24xlarge": {"vcpu":96,  "ram":384,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"General Purpose"},
    "m5d.large":    {"vcpu":2,   "ram":8,     "storage":"75 GB NVMe SSD",    "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5d.xlarge":   {"vcpu":4,   "ram":16,    "storage":"150 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5d.2xlarge":  {"vcpu":8,   "ram":32,    "storage":"300 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5d.4xlarge":  {"vcpu":16,  "ram":64,    "storage":"600 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"General Purpose"},
    "m5d.8xlarge":  {"vcpu":32,  "ram":128,   "storage":"1200 GB NVMe SSD",  "network":"10 Gigabit",        "family":"General Purpose"},
    "m5d.12xlarge": {"vcpu":48,  "ram":192,   "storage":"1800 GB NVMe SSD",  "network":"12 Gigabit",        "family":"General Purpose"},
    "m5d.16xlarge": {"vcpu":64,  "ram":256,   "storage":"2400 GB NVMe SSD",  "network":"20 Gigabit",        "family":"General Purpose"},
    "m5d.24xlarge": {"vcpu":96,  "ram":384,   "storage":"3600 GB NVMe SSD",  "network":"25 Gigabit",        "family":"General Purpose"},
    "c4.large":     {"vcpu":2,   "ram":3.75,  "storage":"EBS only",          "network":"Moderate",          "family":"Compute Optimized"},
    "c4.xlarge":    {"vcpu":4,   "ram":7.5,   "storage":"EBS only",          "network":"High",              "family":"Compute Optimized"},
    "c4.2xlarge":   {"vcpu":8,   "ram":15,    "storage":"EBS only",          "network":"High",              "family":"Compute Optimized"},
    "c4.4xlarge":   {"vcpu":16,  "ram":30,    "storage":"EBS only",          "network":"High",              "family":"Compute Optimized"},
    "c4.8xlarge":   {"vcpu":36,  "ram":60,    "storage":"EBS only",          "network":"10 Gigabit",        "family":"Compute Optimized"},
    "c5.large":     {"vcpu":2,   "ram":4,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5.xlarge":    {"vcpu":4,   "ram":8,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5.2xlarge":   {"vcpu":8,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5.4xlarge":   {"vcpu":16,  "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5.9xlarge":   {"vcpu":36,  "ram":72,    "storage":"EBS only",          "network":"12 Gigabit",        "family":"Compute Optimized"},
    "c5.12xlarge":  {"vcpu":48,  "ram":96,    "storage":"EBS only",          "network":"12 Gigabit",        "family":"Compute Optimized"},
    "c5.18xlarge":  {"vcpu":72,  "ram":144,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"Compute Optimized"},
    "c5.24xlarge":  {"vcpu":96,  "ram":192,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"Compute Optimized"},
    "c5a.large":    {"vcpu":2,   "ram":4,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5a.xlarge":   {"vcpu":4,   "ram":8,     "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5a.2xlarge":  {"vcpu":8,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5a.4xlarge":  {"vcpu":16,  "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5a.8xlarge":  {"vcpu":32,  "ram":64,    "storage":"EBS only",          "network":"10 Gigabit",        "family":"Compute Optimized"},
    "c5a.12xlarge": {"vcpu":48,  "ram":96,    "storage":"EBS only",          "network":"12 Gigabit",        "family":"Compute Optimized"},
    "c5a.16xlarge": {"vcpu":64,  "ram":128,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"Compute Optimized"},
    "c5a.24xlarge": {"vcpu":96,  "ram":192,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"Compute Optimized"},
    "c5d.large":    {"vcpu":2,   "ram":4,     "storage":"50 GB NVMe SSD",    "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5d.xlarge":   {"vcpu":4,   "ram":8,     "storage":"100 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5d.2xlarge":  {"vcpu":8,   "ram":16,    "storage":"200 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5d.4xlarge":  {"vcpu":16,  "ram":32,    "storage":"400 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"Compute Optimized"},
    "c5d.9xlarge":  {"vcpu":36,  "ram":72,    "storage":"900 GB NVMe SSD",   "network":"12 Gigabit",        "family":"Compute Optimized"},
    "c5d.12xlarge": {"vcpu":48,  "ram":96,    "storage":"1800 GB NVMe SSD",  "network":"12 Gigabit",        "family":"Compute Optimized"},
    "c5d.18xlarge": {"vcpu":72,  "ram":144,   "storage":"1800 GB NVMe SSD",  "network":"25 Gigabit",        "family":"Compute Optimized"},
    "c5d.24xlarge": {"vcpu":96,  "ram":192,   "storage":"3600 GB NVMe SSD",  "network":"25 Gigabit",        "family":"Compute Optimized"},
    "r5.large":     {"vcpu":2,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5.xlarge":    {"vcpu":4,   "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5.2xlarge":   {"vcpu":8,   "ram":64,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5.4xlarge":   {"vcpu":16,  "ram":128,   "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5.8xlarge":   {"vcpu":32,  "ram":256,   "storage":"EBS only",          "network":"10 Gigabit",        "family":"Memory Optimized"},
    "r5.12xlarge":  {"vcpu":48,  "ram":384,   "storage":"EBS only",          "network":"12 Gigabit",        "family":"Memory Optimized"},
    "r5.16xlarge":  {"vcpu":64,  "ram":512,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"Memory Optimized"},
    "r5.24xlarge":  {"vcpu":96,  "ram":768,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"Memory Optimized"},
    "r5a.large":    {"vcpu":2,   "ram":16,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5a.xlarge":   {"vcpu":4,   "ram":32,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5a.2xlarge":  {"vcpu":8,   "ram":64,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5a.4xlarge":  {"vcpu":16,  "ram":128,   "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "r5a.8xlarge":  {"vcpu":32,  "ram":256,   "storage":"EBS only",          "network":"10 Gigabit",        "family":"Memory Optimized"},
    "r5a.12xlarge": {"vcpu":48,  "ram":384,   "storage":"EBS only",          "network":"12 Gigabit",        "family":"Memory Optimized"},
    "r5a.16xlarge": {"vcpu":64,  "ram":512,   "storage":"EBS only",          "network":"20 Gigabit",        "family":"Memory Optimized"},
    "r5a.24xlarge": {"vcpu":96,  "ram":768,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"Memory Optimized"},
    "p3.2xlarge":   {"vcpu":8,   "ram":61,    "storage":"EBS only",          "network":"Up to 10 Gigabit",  "family":"GPU"},
    "p3.8xlarge":   {"vcpu":32,  "ram":244,   "storage":"EBS only",          "network":"10 Gigabit",        "family":"GPU"},
    "p3.16xlarge":  {"vcpu":64,  "ram":488,   "storage":"EBS only",          "network":"25 Gigabit",        "family":"GPU"},
    "g4dn.xlarge":  {"vcpu":4,   "ram":16,    "storage":"125 GB NVMe SSD",   "network":"Up to 25 Gigabit",  "family":"GPU"},
    "g4dn.2xlarge": {"vcpu":8,   "ram":32,    "storage":"225 GB NVMe SSD",   "network":"Up to 25 Gigabit",  "family":"GPU"},
    "g4dn.4xlarge": {"vcpu":16,  "ram":64,    "storage":"225 GB NVMe SSD",   "network":"Up to 25 Gigabit",  "family":"GPU"},
    "g4dn.8xlarge": {"vcpu":32,  "ram":128,   "storage":"900 GB NVMe SSD",   "network":"50 Gigabit",        "family":"GPU"},
    "g4dn.16xlarge":{"vcpu":64,  "ram":256,   "storage":"900 GB NVMe SSD",   "network":"50 Gigabit",        "family":"GPU"},
    "i3.large":     {"vcpu":2,   "ram":15.25, "storage":"475 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"Storage Optimized"},
    "i3.xlarge":    {"vcpu":4,   "ram":30.5,  "storage":"950 GB NVMe SSD",   "network":"Up to 10 Gigabit",  "family":"Storage Optimized"},
    "i3.2xlarge":   {"vcpu":8,   "ram":61,    "storage":"1900 GB NVMe SSD",  "network":"Up to 10 Gigabit",  "family":"Storage Optimized"},
    "i3.4xlarge":   {"vcpu":16,  "ram":122,   "storage":"3800 GB NVMe SSD",  "network":"Up to 10 Gigabit",  "family":"Storage Optimized"},
    "i3.8xlarge":   {"vcpu":32,  "ram":244,   "storage":"7600 GB NVMe SSD",  "network":"10 Gigabit",        "family":"Storage Optimized"},
    "i3.16xlarge":  {"vcpu":64,  "ram":488,   "storage":"15200 GB NVMe SSD", "network":"25 Gigabit",        "family":"Storage Optimized"},
    "x1e.xlarge":   {"vcpu":4,   "ram":122,   "storage":"120 GB SSD",        "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "x1e.2xlarge":  {"vcpu":8,   "ram":244,   "storage":"240 GB SSD",        "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "x1e.4xlarge":  {"vcpu":16,  "ram":488,   "storage":"480 GB SSD",        "network":"Up to 10 Gigabit",  "family":"Memory Optimized"},
    "x1e.8xlarge":  {"vcpu":32,  "ram":976,   "storage":"960 GB SSD",        "network":"10 Gigabit",        "family":"Memory Optimized"},
    "x1e.16xlarge": {"vcpu":64,  "ram":1952,  "storage":"1920 GB SSD",       "network":"25 Gigabit",        "family":"Memory Optimized"},
    "x1e.32xlarge": {"vcpu":128, "ram":3904,  "storage":"3840 GB SSD",       "network":"25 Gigabit",        "family":"Memory Optimized"},
}

AWS_HOURLY_PRICES = {
    "t2.nano":0.0058,  "t2.micro":0.0116, "t2.small":0.023,   "t2.medium":0.0464,
    "t2.large":0.0928, "t2.xlarge":0.1856,"t2.2xlarge":0.3712,
    "t3.nano":0.0052,  "t3.micro":0.0104, "t3.small":0.0208,  "t3.medium":0.0416,
    "t3.large":0.0832, "t3.xlarge":0.1664,"t3.2xlarge":0.3328,
    "t3a.nano":0.0047, "t3a.micro":0.0094,"t3a.small":0.0188, "t3a.medium":0.0376,
    "t3a.large":0.0752,"t3a.xlarge":0.1504,"t3a.2xlarge":0.3008,
    "m5.large":0.096,  "m5.xlarge":0.192, "m5.2xlarge":0.384, "m5.4xlarge":0.768,
    "m5.8xlarge":1.536,"m5.12xlarge":2.304,"m5.16xlarge":3.072,"m5.24xlarge":4.608,
    "m5a.large":0.086, "m5a.xlarge":0.172,"m5a.2xlarge":0.344,"m5a.4xlarge":0.688,
    "m5a.8xlarge":1.376,"m5a.12xlarge":2.064,"m5a.16xlarge":2.752,"m5a.24xlarge":4.128,
    "m5d.large":0.113, "m5d.xlarge":0.226,"m5d.2xlarge":0.452,"m5d.4xlarge":0.904,
    "m5d.8xlarge":1.808,"m5d.12xlarge":2.712,"m5d.16xlarge":3.616,"m5d.24xlarge":5.424,
    "c4.large":0.1,    "c4.xlarge":0.199, "c4.2xlarge":0.398, "c4.4xlarge":0.796,  "c4.8xlarge":1.591,
    "c5.large":0.085,  "c5.xlarge":0.17,  "c5.2xlarge":0.34,  "c5.4xlarge":0.68,
    "c5.9xlarge":1.53, "c5.12xlarge":2.04,"c5.18xlarge":3.06, "c5.24xlarge":4.08,
    "c5a.large":0.077, "c5a.xlarge":0.154,"c5a.2xlarge":0.308,"c5a.4xlarge":0.616,
    "c5a.8xlarge":1.232,"c5a.12xlarge":1.848,"c5a.16xlarge":2.464,"c5a.24xlarge":3.696,
    "c5d.large":0.096, "c5d.xlarge":0.192,"c5d.2xlarge":0.384,"c5d.4xlarge":0.768,
    "c5d.9xlarge":1.728,"c5d.12xlarge":2.304,"c5d.18xlarge":3.456,"c5d.24xlarge":4.608,
    "r5.large":0.126,  "r5.xlarge":0.252, "r5.2xlarge":0.504, "r5.4xlarge":1.008,
    "r5.8xlarge":2.016,"r5.12xlarge":3.024,"r5.16xlarge":4.032,"r5.24xlarge":6.048,
    "r5a.large":0.113, "r5a.xlarge":0.226,"r5a.2xlarge":0.452,"r5a.4xlarge":0.904,
    "r5a.8xlarge":1.808,"r5a.12xlarge":2.712,"r5a.16xlarge":3.616,"r5a.24xlarge":5.424,
    "p3.2xlarge":3.06, "p3.8xlarge":12.24,"p3.16xlarge":24.48,
    "g4dn.xlarge":0.526,"g4dn.2xlarge":0.752,"g4dn.4xlarge":1.204,
    "g4dn.8xlarge":2.264,"g4dn.16xlarge":4.528,
    "i3.large":0.156,  "i3.xlarge":0.312, "i3.2xlarge":0.624, "i3.4xlarge":1.248,
    "i3.8xlarge":2.496,"i3.16xlarge":4.992,
    "x1e.xlarge":0.834,"x1e.2xlarge":1.668,"x1e.4xlarge":3.336,"x1e.8xlarge":6.672,
    "x1e.16xlarge":13.344,"x1e.32xlarge":26.688,
}

def filter_instances(vcpu_min=None, vcpu_max=None, ram_min=None, ram_max=None, min_storage=None, family=None, search=None):
    results = []
    for name, spec in INSTANCES.items():
        if vcpu_min and spec["vcpu"] < vcpu_min: continue
        if vcpu_max and spec["vcpu"] > vcpu_max: continue
        if ram_min and spec["ram"] < ram_min: continue
        if ram_max and spec["ram"] > ram_max: continue
        if family and family != "All" and spec["family"] != family: continue
        if search and search.lower() not in name.lower(): continue
        if min_storage and min_storage > 0:
            if spec["storage"] == "EBS only": continue
            try:
                gb = int(spec["storage"].split(" ")[0])
                if gb < min_storage: continue
            except: continue
        hourly = AWS_HOURLY_PRICES.get(name, 0)
        results.append({
            "instance_type": name,
            "vcpu": spec["vcpu"],
            "ram": spec["ram"],
            "storage": spec["storage"],
            "network": spec["network"],
            "family": spec["family"],
            "aws_hourly": hourly,
            "aws_monthly": round(hourly * 720, 2),
        })
    return sorted(results, key=lambda x: x["aws_monthly"])

FAMILIES = ["All", "General Purpose", "Compute Optimized", "Memory Optimized", "Storage Optimized", "GPU"]
